### PR TITLE
Added hire command and more...

### PR DESCRIPTION
**Pull request by Soheab**
- Added hire command, see the docstring.
- Improved fire command a bit:
-- Prevent a admin from firing themself, this will send a (nice) message 
-- Added some text when member didn't have any bots with the staff bot role.
-- Remove the added reactions when confirmed or timeout.
-- Edits the original message now instead of sending a new one.
- Fixed botinfo not sending in the verification server.
- Added part in on_member_join to add the mod role to joining humans in the verification server.
- Improved the dm command by adding arguments and flags, see the docstring/code.
- Fixed hyperlink on title for queue command.

### CODE REVIEW

**Comment by DylanD16** [comment]
You could add a signature to the bottom of the message...
Example:
{ctx.author.name}, {ctx.author.top_role.name}

Print:
Dylster, Senior Website Moderator

This could also be as a parser thing like [SIGNATURE]

**Comment by Soheab** [comment]
> You could add a signature to the bottom of the message...
> Example:
> {ctx.author.name}, {ctx.author.top_role.name}
> 
> Print:
> Dylster, Senior Website Moderator
> 
> This could also be as a parser thing like [SIGNATURE]

Sure, i can add that as default with a flag to change it if you want.

**Comment by DylanD16** [comment]
> Sure, i can add that as default with a flag to change it if you want.

Yeah, so as a flag like --signature rather than [SIGNATURE]?

**Comment by Soheab** [comment]
> 
> > Sure, i can add that as default with a flag to change it if you want.
> 
> Yeah, so as a flag like --signature rather than [SIGNATURE]? 

Yes because in my opinion a SIGNATURE argument would be useless because it's only going to be used at the end, this is something that can be "hardcoded(?)" and changed if wanted with the mentioned flag.

**Comment by DylanD16** [comment]
> Yes because in my opinion a SIGNATURE argument would be useless because it's only going to be used at the end, this is something that can be "hardcoded(?)" and changed if wanted with the mentioned flag.

Makes sense

**Comment by GavynStanley** [comment]
Will all of this actually work this time or are you giving me more broken shit

**Comment by Soheab** [comment]
> Will all of this actually work this time or are you giving me more broken shit

Most things are tested this time.

**Pull request merged**
